[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimshell'
rev  = '3787e5'

[[plugins]]
repo = 'MaxMEllon/molokai'
# hook_add = '''
#   syntax on
#   set t_Co=256
#   try
#     colorscheme molokai
#     let g:molokai_original = 1
#   catch
#     colorscheme desert
#   endtry
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  syntax on
  set t_Co=256
  try
    colorscheme iceberg
  catch
    colorscheme desert
  endtry
'''

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''
  syntax on
  set t_Co=256
  try
    colorscheme vim-lucius
  catch
    colorscheme desert
  endtry
  set background=dark
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_faster = 1
  nmap <silent><Leader>i :<C-u>IndentLinesToggle<CR>
  let g:indentLine_color_term = 111
  let g:indentLine_color_gui = '#708090'
  let g:indentLine_char = '¦'
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'default',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'fugitive': 'LightLineFugitive',
    \ },
    \ }
  function! LightLineFugitive()
    return exists('*fugitive#head') ? fugitive#head() : ''
  endfunction
  set laststatus=2
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['rb', 'erb']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['rb', 'erb']

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
  let g:auto_ctags = 1
  set tags=./tags
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
hook_add = '''
  au BufRead,BufNewFile,BufReadPre *.coffee set filetype=coffee
'''
